language: node_js
node_js:
  - node
addons:
  apt:
    packages:
      - nodejs-legacy
install:
  - npm install
after_success:
  - cat ./dist/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js